### ISSUE TITLE
Cannot read property 'display_name' of undefined

### ISSUE THREAD

**Issue by maikondouglas** [RocketChat/docs-old#1987] opened 2021-05-31 17:39 UTC
In the pullrequest:created action when selecting reviewers this problem occurs

**Comment by maikondouglas** [comment] 2021-06-06 23:13
@d-gubert Can you help me with this? I'm in the testing period and I intend to use a tool to integrate with Bitbucket, but only if it works as Pull Request write actions

**Comment by d-gubert** [comment] 2021-06-09 13:19
Hey @maikondouglas, have you tried reaching the support channel indicated by the app? That would be the optimal way for getting help with our paid apps, as this repo is for our docs and is **not** related to apps, or even monitored for problems with them.

I can confirm that the Bitbucket Cloud app reacts only to the following events:
* repo:push
* pullrequest:created
* pullrequest:rejected
* pullrequest:approved
* pullrequest:fulfilled

Regarding the `display_name` problem, it seems to be the case where a reviewer of the pull request is missing this field.

I'll be closing this issue as it is not related to the docs repo :)

**Closed as completed by d-gubert** 2021-06-09 13:19 UTC
