### ISSUE TITLE
Add examples for custom themings

### ISSUE THREAD

**Issue by juliagrala** [RocketChat/docs-old#556] opened 2018-02-08 12:37 UTC
https://rocket.chat/docs/developer-guides/ui-and-theming/

Add theming examples to help people to visualize how Rocket.Chat can look like and help beginners to code.  

Client feedback and experience:
"Customize the user interface is a very important point in keeping users active and loyal, to the point of promoting the community. I asked the support how to change colors and RC sources. They gave me this link that talks about possibilities. As I am new to html, php, css ... I asked for examples of how other communities did this because it is much simpler for me to modify existing / valid code than to develop from scratch."

**Comment by MartinSchoeler** [comment] 2018-02-08 12:59
@juliagrala Regarding this issue, we have some things to put in mind:
- Today we have the layout section, which is a more user friendly way to customize rocket.chat
- The theming documentation is very outdated, and i'm not even sure if the theming feature is working as intended
- We are going under heavy changes on the Interface, so any themes created would become outdated really fast 

So i think we must wait for the UI Redesign to be ready to start touching theming again. For now we should be directing users to the Layout section of Rocket.Chat settings

**Comment by MartinSchoeler** [comment] 2018-02-08 13:07
Theming will have heavy changes after the redesign, so i will be closing this. Let's discuss this again after the redesign.

**Closed as completed by MartinSchoeler** 2018-02-08 13:07 UTC
