### ISSUE TITLE
Welcome page has broken image

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/docs-old#95] opened 2016-09-21 19:49 UTC
![image](https://cloud.githubusercontent.com/assets/1000217/18726551/5e821d60-801b-11e6-971a-aa5f38cad611.png)

**Comment by graywolf336** [comment] 2016-11-29 21:27
This is caused by https://github.com/RocketChat/Rocket.Chat.Docs.Generator/issues/7

**Comment by frdmn** [comment] 2016-11-30 08:39
Is this still an issue? Because the prod docs looks fine for me, local build doesn't show missing images either.

**Comment by karlprieb** [comment] 2016-11-30 11:19
Still have problems in prod. The path is missing if you change the route.

![2016-11-30 09 16 08](https://cloud.githubusercontent.com/assets/9200155/20750416/e50d8222-b6dd-11e6-9578-354d4bbff0c3.gif)

**Comment by graywolf336** [comment] 2016-11-30 11:43
This will be fixed once https://github.com/RocketChat/Rocket.Chat.Docs.Generator/issues/7 is closed :)

**Comment by frdmn** [comment] 2016-11-30 11:44
Working on this as we speak.

**Comment by graywolf336** [comment] 2016-11-30 11:46
@frdmn I am working on it as well, it is because we switched over to Senna.js and is a result of how they push the state. See: https://github.com/liferay/senna.js/issues/131

**Comment by frdmn** [comment] 2016-11-30 11:53
@graywolf336 Ha! Okay, then I'll stop what I do right now. Added my current thoughts as comment in RocketChat/Rocket.Chat.Docs.Generator#7 though

**Comment by graywolf336** [comment] 2016-11-30 11:57
@frdmn I should have said something, as I started work on it last night 😬

**Closed as completed** 2016-11-30 14:19 UTC
